# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: ServerManager

pool:
  vmImage: windows-2022

steps:
- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'CSGO-ServerManager-Extended/CSGO-ServerManager-Extended/CSGO-ServerManager-Extended.csproj'
    arguments: '-c Release -f net6.0-android'

- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.aab'
    jarsign: true
    jarsignerKeystoreFile: 'ServerManager.keystore'
    jarsignerKeystorePassword: '$(keystore-password)'
    jarsignerKeystoreAlias: 'ServerManager'
    jarsignerKeyPassword: '$(key-password)'
    jarsignerArguments: '-sigalg SHA256withRSA -digestalg SHA-256'
    zipalign: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.aab'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'